name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - IPython=8.4.0
  - ipykernel=6.15.1
  - ipywidgets=8.0.1
  - jupyterlab=3.0.12
  - notebook=6.4.12
  - pandas-profiling=2.11.0
  - pandas=1.2.3
  - pip=22.2.2  
  - pip:
      - wandb==0.13.2